# Nénuphar Projects

[Configuration]
Location = "Config"

[Project.Engine]
Name = "NenupharEngine"
Version = "0.0.1"
Location = "Source/Engine"
BinariesLocation = "Bin/Engine"
BuildLocation = "Build/Engine"
CPPVersion = "20"


[Project.Editor]
Name = "NenupharEditor"
Version = "0.0.1"
Location = "Source/Editor"
BinariesLocation = "Bin/Editor"
BuildLocation = "Build/Editor"
CPPVersion = "20"

