
[Module]
Name = "NenupharEditor.Application"
OutputType = "Executable"
Dependencies = [
  { Name = "NenupharEditor.Core" },
  { Name = "NenupharEngine.Core" },
  { Name = "NenupharEngine.ApplicationCore" },
]

